name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install client dependencies
        run: cd client && yarn install --frozen-lockfile

      - name: Build
        run: cd .. && yarn build

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ ! -d "/root/apps/univille" ] ; then
              git clone https://github.com/OferElfassi/univille-fs.git /root/apps/univille
            fi
            cd /root/apps/univille
            git pull
            yarn install
            yarn build
            if ! pm2 describe univille-fs >/dev/null 2>&1 ; then
              pm2 start /root/apps/univille/build/index.js --name "univille-fs"
            else
              pm2 restart univille-fs
            fi
